kinetica_cluster_reconciler.yaml: |2-
    Version: v7.1.9.5
    TargetProvider: "on-prem"
    ComponentConfig:
        SystemNamespace: "{{ .Release.Namespace }}"
        DBNamespace: "{{ .Values.kineticacluster.namespace }}"
        LDAP:
          IsExternal: false
          Internal:
              Name: "openldap"
              Namespace: "{{ .Values.kineticacluster.namespace }}"
        Nginx:
          Namespace: "{{ .Release.Namespace }}"
    KineticaClusterAdminReconcilerConfig:
      Debug: false
    KineticaClusterBackupReconcilerConfig:
      Debug: false
    KineticaClusterGrantReconcilerConfig:
      Debug: false
    KineticaClusterReconcilerConfig:
      Debug: false
      IsSaaS: false
    KineticaClusterRestoreReconcilerConfig:
      Debug: false
    KineticaClusterRoleReconcilerConfig:
      Debug: false
    KineticaClusterScheduleReconcilerConfig:
      Debug: false
    KineticaClusterUpgradeReconcilerConfig:
      Debug: false
    KineticaClusterUserReconcilerConfig:
      Debug: false
    KineticaClusterResourceGroupReconcilerConfig:
        Debug: false
    KineticaClusterSchemaReconcilerConfig:
        Debug: false
